name: CI cmd

on:
  pull_request_target:
    paths:
      - 'git/**'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 'stable'

    - name: Checkout
      uses: actions/checkout@v3
      with:
        ref: ${{ github.event.pull_request.head.sha }}
        fetch-depth: 0      

    - name: Get branch information
      run: |
        BRANCH_NAME=$(jq --raw-output .pull_request.head.ref $GITHUB_EVENT_PATH)
        UPSTREAM_BRANCH=$(jq --raw-output .pull_request.base.ref $GITHUB_EVENT_PATH)
        git fetch origin $UPSTREAM_BRANCH
        git diff --quiet $UPSTREAM_BRANCH..$BRANCH_NAME || echo "Branch is behind upstream"

    - name: Cache Go - Modules
      uses: actions/cache@v3
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-

    - name: Test 
      run: go test -v ./...


