name: CI cmd


on:
  pull_request_target:
    paths:
      - 'git/**'

jobs:
  call-workflow-ci-cmd:
    uses: untillpro/ci-action/.github/workflows/ci_reuse_go_pr.yml@master
    with: 
      test_folder: '.'
      ignore_bp3: 'true'
    secrets:
      reporeading_token: ${{ secrets.REPOREADING_TOKEN }}
      codecov_token: ${{ secrets.CODECOV_TOKEN }}
      personal_token: ${{ secrets.PERSONAL_TOKEN }}



