name: CI cmd

on:
  push:
    paths:
      - 'git/**'

jobs:
  call-workflow-ci-cmd:
    uses: untillpro/ci-action/.github/workflows/ci_reuse_go.yml@master
    with: 
      test_folder: '.'
      ignore_bp3: 'true'
    secrets:
      reporeading_token: ${{ secrets.REPOREADING_TOKEN }}
      codecov_token: ${{ secrets.CODECOV_TOKEN }}
      personal_token: ${{ secrets.PERSONAL_TOKEN }}

