name: CI cmd

on:
  push:
    paths:
      - 'git/**'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 'stable'

    - name: Checkout
      uses: actions/checkout@v3

    - name: Cache Go - Modules
      uses: actions/cache@v3
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-

    - name: Test 
      run: go test -v ./...


